server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp 

  datasource:
    url: jdbc:mysql://localhost:3306/portfolio?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  # sql:
  #   init:
  #     mode: always

  data:
    mongodb:
      uri: mongodb://localhost:27017/portfolio

  jpa:
    # defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      # ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  output:
    ansi:
      enabled: always

# S3 설정
cloud:
  aws:
    region:
      static: ${STATIC}
      auto: false # false면 자동으로 리전을 선택하지 않고, static 설정을 따름
    s3:
      bucket: ${BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    stack:
      auto: false # false로 설정된 경우, CloudFormation 스택은 자동으로 생성되거나 관리되지 않음

# Sentry 설정
sentry:
  dsn: ${SENTRY_DSN}
  enable-tracing: true     # 성능 데이터 전송
  send-default-pii: true   # 사용자의 정보 포함
  environment: development # 필터링에 사용
  logging:
    minimum-event-level: "WARN"      # 명시 레벨 이상의 로그 이벤트를 Sentry로 전송
    minimum-breadcrumb-level: "INFO" # INFO 레벨 이상의 breadcrumb만 기록
  sample-rate: 1 # 이벤트 샘플링 비율 설정 (1: 100%, 0.1: 10% 등) 


name: ${MY_JWT}